#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.Auth.Domain </Project>
//     <File> 
//         <Name> EntityBase.cs </Name>
//         <Created> 27 03 2017 02:39:27 PM </Created>
//         <Key> 9BBFB04B-177D-4D87-B047-2F94F957E579 </Key>
//     </File>
//     <Summary>
//         EntityBase is abstract entity to another entity inherit
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Newtonsoft.Json;
using Puppy.Core.DateTimeUtils;

namespace Puppy.EF
{
    public interface IBaseEntity
    {
        string GlobalId { get; set; }

        DateTimeOffset CreatedTime { get; set; }

        DateTimeOffset? LastUpdatedTime { get; set; }

        bool IsDeleted { get; set; }

        DateTimeOffset? DeletedTime { get; set; }

        [Timestamp]
        byte[] Version { get; set; }
    }

    /// <summary>
    /// Entity Base for Entity Framework
    /// </summary>
    /// <typeparam name="TId">Id type of this entity</typeparam>
    /// <typeparam name="TOwnerId">Id type of who do the action of entity (for tracking)</typeparam>
    public abstract class EntityBase<TId, TOwnerId> : IBaseEntity
    {
        [Key]
        public virtual TId Id { get; set; }

        public virtual string GlobalId { get; set; } = Guid.NewGuid().ToString("N");

        public virtual DateTimeOffset CreatedTime { get; set; } = DateTimeOffset.UtcNow;

        /// <summary>
        /// For tracking
        /// </summary>
        public virtual TOwnerId CreatedBy { get; set; }

        public virtual DateTimeOffset? LastUpdatedTime { get; set; }

        /// <summary>
        /// For tracking
        /// </summary>
        public virtual TOwnerId UpdatedBy { get; set; }

        public virtual bool IsDeleted { get; set; }

        public virtual DateTimeOffset? DeletedTime { get; set; }

        /// <summary>
        /// For tracking
        /// </summary>
        public virtual TOwnerId DeletedBy { get; set; }

        [Timestamp]
        public virtual byte[] Version { get; set; }
    }

    public class EntityBase : EntityBase<int, int?>
    {
        public override int? CreatedBy { get; set; }

        public override int? UpdatedBy { get; set; }

        public override int? DeletedBy { get; set; }
    }
}