#region	License
//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.Auth.Service.Facade </Project>
//     <File> 
//         <Name> ProfileService.cs </Name>
//         <Created> 29 03 2017 11:55:30 PM </Created>
//         <Key> 6B0A8F26-EBEE-4D43-8F5B-6A851550F37D </Key>
//     </File>
//     <Summary>
//         ProfileService
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------
#endregion License

using System.Threading.Tasks;
using IdentityServer4.Models;
using TopCore.Auth.Business;
using TopCore.Framework.DependencyInjection.Attributes;

namespace TopCore.Auth.Service.Facade
{
    [PerRequestDependency(ServiceType = typeof(IProfileService))]
    public class ProfileService : IProfileService
    {
    }
}