#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.Auth.Domain </Project>
//     <File> 
//         <Name> EntityBase.cs </Name>
//         <Created> 27 03 2017 02:39:27 PM </Created>
//         <Key> 9BBFB04B-177D-4D87-B047-2F94F957E579 </Key>
//     </File>
//     <Summary>
//         EntityBase is abstract entity to another entity inherit
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using System;
using System.ComponentModel.DataAnnotations;

namespace TopCore.Auth.Domain.Entities
{
    public abstract class EntityBase
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Unique key
        /// </summary>
        public Guid Key { get; set; } = Guid.NewGuid();

        public bool IsDeleted { get; set; }

        public DateTime CreatedOnUtc { get; set; }

        public DateTime? LastUpdatedOnUtc { get; set; }

        public DateTime? DeletedOnUtc { get; set; }

        [Timestamp]
        public byte[] Version { get; set; }
    }
}