#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.WebAPI </Project>
//     <File> 
//         <Name> BaseEntity.cs </Name>
//         <Created> 27 03 2017 02:39:27 PM </Created>
//         <Key> 9BBFB04B-177D-4D87-B047-2F94F957E579 </Key>
//     </File>
//     <Summary>
//         BaseEntity is abstract entity to another entity inherit
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using System;

namespace TopCore.DAL.Entity
{
    public abstract class BaseEntity
    {
        protected BaseEntity()
        {
            Key = Guid.NewGuid().ToString("N");
            CreateOnUtc = DateTime.UtcNow;
        }

        public long Id { get; set; }
        public string Key { get; set; }
        public DateTime CreateOnUtc { get; set; }
    }
}