#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.DAL </Project>
//     <File> 
//         <Name> UserEntity.cs </Name>
//         <Created> 27 03 2017 02:38:26 PM </Created>
//         <Key> F38D22F5-AEB6-4A7E-A057-29DDD8FC24BD </Key>
//     </File>
//     <Summary>
//         UserEntity
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

namespace TopCore.DAL.Entity
{
    public class UserEntity : BaseEntity
    {

    }
}