#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.Data.EF </Project>
//     <File> 
//         <Name> Program.cs </Name>
//         <Created> 28 03 2017 05:00:26 PM </Created>
//         <Key> D01A2F51-E357-42E6-A8E7-0D932965FA23 </Key>
//     </File>
//     <Summary>
//         Program
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

namespace TopCore.Data.EF
{
    public class Program
    {
        public static void Main(string[] args)
        {
        }
    }
}