#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.WebAPI.Data </Project>
//     <File> 
//         <Name> UserEntity.cs </Name>
//         <Created> 27 03 2017 02:38:26 PM </Created>
//         <Key> F38D22F5-AEB6-4A7E-A057-29DDD8FC24BD </Key>
//     </File>
//     <Summary>
//         UserEntity
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using System;
using TopCore.Framework.EF;

namespace TopCore.WebAPI.Data.Entity
{
    public class User : EntityBase
    {
        public User(int createdBy) : base(createdBy)
        {
        }

        public string UserName { get; set; }
    }
}