#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.SSO.Data.EF </Project>
//     <File> 
//         <Name> TopCoreSSODbContext.SSOContextFactory.cs </Name>
//         <Created> 28 03 2017 05:50:31 PM </Created>
//         <Key> 0679F181-B40B-49BF-A6A6-1AFA54A83376 </Key>
//     </File>
//     <Summary>
//         TopCoreSSODbContext.SSOContextFactory
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TopCore.Framework.Core;

namespace TopCore.SSO.Data.EF
{
    public class TopCoreSSODbContextFactory : IDbContextFactory<TopCoreSSODbContext>
    {
        public TopCoreSSODbContext Create(DbContextFactoryOptions options)
        {
            var connectionString = GetConnectionString(options);
            return CreateCoreContext(connectionString);
        }

        /// <summary>
        /// Get connection from DbContextFactoryOptions Environment
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        private string GetConnectionString(DbContextFactoryOptions options)
        {
            var connectionString = ConfigHelper.GetValue("appsettings.json", $"ConnectionStrings:{options.EnvironmentName}");
            return connectionString;
        }

        private static TopCoreSSODbContext CreateCoreContext(string connectionString)
        {
            var builder = new DbContextOptionsBuilder<TopCoreSSODbContext>();
            builder.UseSqlServer(connectionString);
            return new TopCoreSSODbContext(builder.Options);
        }
    }
}