#region	License
//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.WebAPI.Service </Project>
//     <File>
//         <Name> IUserService </Name>
//         <Created> 29 03 2017 11:53:37 PM </Created>
//         <Key> 7C89D71B-5817-4B8F-B34C-760E13B597BC </Key>
//     </File>
//     <Summary>
//         IUserService
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------
#endregion License

namespace TopCore.WebAPI.Service
{
    public interface IUserService
    {
        string GetUserName();
    }
}