#region	License

//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.API </Project>
//     <File> 
//         <Name> Program.cs </Name>
//         <Created> 28 03 2017 10:19:01 AM </Created>
//         <Key> 29832439-583C-47C6-A80F-B93105D7109D </Key>
//     </File>
//     <Summary>
//         Program
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------

#endregion License

using Microsoft.AspNetCore.Hosting;
using System.IO;
using TopCore.Framework.Web;

namespace TopCore.WebAPI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            IWebHostBuilder hostBuilder =
                new WebHostBuilder()
                    .UseKestrel()
                    .UseWebRoot(Domain.Constants.Web.WebRoot)
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseIISIntegration()
                    .UseStartup<Startup>();

#if DEBUG
            hostBuilder.BuildAndRunWithBrowser();
#else
            hostBuilder.BuildAndRun();
#endif
        }
    }
}