namespace TopCore.Framework.Search.Elastic.Model.SearchModel.Aggregations
{
    /// <summary>
    ///     A single-value metrics aggregation that keeps track and returns the minimum value among
    ///     numeric values extracted from the aggregated documents. These values can be extracted
    ///     either from specific numeric fields in the documents, or be generated by a provided script.
    /// </summary>
    public class MinMetricAggregation : BaseMetricAggregation
    {
        public MinMetricAggregation(string name, string field) : base("min", name, field)
        {
        }

        public override void WriteJson(ElasticJsonWriter elasticCrudJsonWriter)
        {
            WriteJsonBase(elasticCrudJsonWriter, WriteValues);
        }

        private void WriteValues(ElasticJsonWriter elasticCrudJsonWriter)
        {
        }
    }
}