#region	License
//------------------------------------------------------------------------------------------------
// <Auto-generated>
//     <Author> Top Nguyen (http://topnguyen.net) </Author>
//     <Project> TopCore.Auth.Service </Project>
//     <File>
//         <Name> IUserService </Name>
//         <Created> 29 03 2017 11:53:37 PM </Created>
//         <Key> 7C89D71B-5817-4B8F-B34C-760E13B597BC </Key>
//     </File>
//     <Summary>
//         IUserService
//     </Summary>
// </Auto-generated>
//------------------------------------------------------------------------------------------------
#endregion License

using System.Threading.Tasks;
using IdentityServer4.Models;

namespace TopCore.Auth.Service
{
    public interface IProfileService
    {
    }
}